<a href="https://colab.research.google.com/github/MdMonirulIslam59335404/monirul/blob/main/heart_attack_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# prompt: give code to upload a csv datasheet file in python

from google.colab import files
import pandas as pd

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

  # Assuming the uploaded file is a CSV
  try:
    df = pd.read_csv(fn)
    print(df.head())  # Display the first few rows of the DataFrame
  except pd.errors.ParserError:
    print(f"Error: Could not parse {fn} as a CSV file.")
  except Exception as e:
    print(f"An unexpected error occurred: {e}")

Saving heart_attack_prediction_india.csv to heart_attack_prediction_india.csv
User uploaded file "heart_attack_prediction_india.csv" with length 850422 bytes
   Patient_ID        State_Name  Age  Gender  Diabetes  Hypertension  Obesity  \
0           1         Rajasthan   42  Female         0             0        1
1           2  Himachal Pradesh   26    Male         0             0        0
2           3             Assam   78    Male         0             0        1
3           4            Odisha   58    Male         1             0        1
4           5         Karnataka   22    Male         0             0        0

   Smoking  Alcohol_Consumption  Physical_Activity  ...  Diastolic_BP  \
0        1                    0                  0  ...           119
1        0                    1                  1  ...           115
2        0                    0                  1  ...           117
3        0                    0                  1  ...            65
4        0                    0                  1  ...           109

   Air_Pollution_Exposure  Family_History  Stress_Level  Healthcare_Access  \
0                       1               0             4                  0
1                       0               0             7                  0
2                       0               1            10                  1
3                       0               0             1                  1
4                       0               0             9                  0

   Heart_Attack_History  Emergency_Response_Time  Annual_Income  \
0                     0                      157         611025
1                     0                      331         174527
2                     0                      186        1760112
3                     1                      324        1398213
4                     0                      209          97987

   Health_Insurance  Heart_Attack_Risk
0                 0                  0
1                 0                  0
2                 1                  0
3                 0                  0
4                 0                  1

[5 rows x 26 columns]

In [6]:
# prompt: code to see  the uploaded datasheet csv

# Now you can work with the dataframe 'df'
df

,Patient_ID,State_Name,Age,Gender,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,...,Diastolic_BP,Air_Pollution_Exposure,Family_History,Stress_Level,Healthcare_Access,Heart_Attack_History,Emergency_Response_Time,Annual_Income,Health_Insurance,Heart_Attack_Risk
0,1,Rajasthan,42,Female,0,0,1,1,0,0,...,119,1,0,4,0,0,157,611025,0,0
1,2,Himachal Pradesh,26,Male,0,0,0,0,1,1,...,115,0,0,7,0,0,331,174527,0,0
2,3,Assam,78,Male,0,0,1,0,0,1,...,117,0,1,10,1,0,186,1760112,1,0
3,4,Odisha,58,Male,1,0,1,0,0,1,...,65,0,0,1,1,1,324,1398213,0,0
4,5,Karnataka,22,Male,0,0,0,0,0,1,...,109,0,0,9,0,0,209,97987,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Maharashtra,20,Female,0,0,0,1,0,1,...,74,1,1,10,0,0,167,1175023,1,0
9996,9997,Rajasthan,34,Female,0,0,0,0,0,0,...,78,0,1,1,0,0,123,999441,0,1
9997,9998,Gujarat,76,Male,0,0,0,0,0,0,...,98,1,0,1,0,1,376,159536,0,0
9998,9999,Andhra Pradesh,52,Male,0,0,0,0,0,1,...,60,1,0,7,1,0,313,153207,0,0
9999,10000,Haryana,25,Female,0,1,0,1,0,1,...,89,1,0,4,0,1,366,1732794,1,0

In [7]:
# prompt: shape of the datasheet

df.shape

(10000, 26)

In [8]:
# prompt: code for data profiling  of that datasheet

# Data type analysis
print(df.dtypes)

# Summary statistics for numerical columns
print(df.describe())

# Missing value analysis
print(df.isnull().sum())

# Unique values per column
for col in df.columns:
  print(f"Unique values in {col}: {df[col].unique()}")
  print(f"Number of unique values in {col}: {df[col].nunique()}")

# Value counts for categorical columns
for col in df.columns:
  if df[col].dtype == 'object':
    print(f"Value counts for {col}:\n{df[col].value_counts()}")

# Correlation analysis (for numerical columns)
print(df.corr())

Patient_ID                  int64
State_Name                 object
Age                         int64
Gender                     object
Diabetes                    int64
Hypertension                int64
Obesity                     int64
Smoking                     int64
Alcohol_Consumption         int64
Physical_Activity           int64
Diet_Score                  int64
Cholesterol_Level           int64
Triglyceride_Level          int64
LDL_Level                   int64
HDL_Level                   int64
Systolic_BP                 int64
Diastolic_BP                int64
Air_Pollution_Exposure      int64
Family_History              int64
Stress_Level                int64
Healthcare_Access           int64
Heart_Attack_History        int64
Emergency_Response_Time     int64
Annual_Income               int64
Health_Insurance            int64
Heart_Attack_Risk           int64
dtype: object
        Patient_ID           Age      Diabetes  Hypertension       Obesity  \
count  10000.00000  10000.000000  10000.000000   10000.00000  10000.000000
mean    5000.50000     49.394900      0.092900       0.24690      0.303700
std     2886.89568     17.280301      0.290307       0.43123      0.459878
min        1.00000     20.000000      0.000000       0.00000      0.000000
25%     2500.75000     35.000000      0.000000       0.00000      0.000000
50%     5000.50000     49.000000      0.000000       0.00000      0.000000
75%     7500.25000     64.000000      0.000000       0.00000      1.000000
max    10000.00000     79.000000      1.000000       1.00000      1.000000

            Smoking  Alcohol_Consumption  Physical_Activity    Diet_Score  \
count  10000.000000         10000.000000       10000.000000  10000.000000
mean       0.301400             0.352800           0.595800      5.021700
std        0.458889             0.477865           0.490761      3.156394
min        0.000000             0.000000           0.000000      0.000000
25%        0.000000             0.000000           0.000000      2.000000
50%        0.000000             0.000000           1.000000      5.000000
75%        1.000000             1.000000           1.000000      8.000000
max        1.000000             1.000000           1.000000     10.000000

       Cholesterol_Level  ...  Diastolic_BP  Air_Pollution_Exposure  \
count       10000.000000  ...  10000.000000            10000.000000
mean          224.753000  ...     89.312000                0.403600
std            43.359172  ...     17.396486                0.490644
min           150.000000  ...     60.000000                0.000000
25%           187.000000  ...     74.000000                0.000000
50%           226.000000  ...     89.000000                0.000000
75%           262.000000  ...    104.000000                1.000000
max           299.000000  ...    119.000000                1.000000

       Family_History  Stress_Level  Healthcare_Access  Heart_Attack_History  \
count    10000.000000  10000.000000       10000.000000          10000.000000
mean         0.311300      5.518800           0.311000              0.152500
std          0.463048      2.866264           0.462926              0.359523
min          0.000000      1.000000           0.000000              0.000000
25%          0.000000      3.000000           0.000000              0.000000
50%          0.000000      6.000000           0.000000              0.000000
75%          1.000000      8.000000           1.000000              0.000000
max          1.000000     10.000000           1.000000              1.000000

       Emergency_Response_Time  Annual_Income  Health_Insurance  \
count             10000.000000   1.000000e+04      10000.000000
mean                206.383400   1.022062e+06          0.344700
std                 112.391711   5.605978e+05          0.475294
min                  10.000000   5.035300e+04          0.000000
25%                 110.000000   5.357838e+05          0.000000
50%                 206.000000   1.021383e+06          0.000000
75%                 304.000000   1.501670e+06          1.000000
max                 399.000000   1.999714e+06          1.000000

       Heart_Attack_Risk
count       10000.000000
mean            0.300700
std             0.458585
min             0.000000
25%             0.000000
50%             0.000000
75%             1.000000
max             1.000000

[8 rows x 24 columns]
Patient_ID                 0
State_Name                 0
Age                        0
Gender                     0
Diabetes                   0
Hypertension               0
Obesity                    0
Smoking                    0
Alcohol_Consumption        0
Physical_Activity          0
Diet_Score                 0
Cholesterol_Level          0
Triglyceride_Level         0
LDL_Level                  0
HDL_Level                  0
Systolic_BP                0
Diastolic_BP               0
Air_Pollution_Exposure     0
Family_History             0
Stress_Level               0
Healthcare_Access          0
Heart_Attack_History       0
Emergency_Response_Time    0
Annual_Income              0
Health_Insurance           0
Heart_Attack_Risk          0
dtype: int64
Unique values in Patient_ID: [    1     2     3 ...  9998  9999 10000]
Number of unique values in Patient_ID: 10000
Unique values in State_Name: ['Rajasthan' 'Himachal Pradesh' 'Assam' 'Odisha' 'Karnataka' 'Tripura'
 'Arunachal Pradesh' 'Uttarakhand' 'Manipur' 'Nagaland' 'West Bengal'
 'Bihar' 'Meghalaya' 'Maharashtra' 'Telangana' 'Tamil Nadu' 'Sikkim'
 'Uttar Pradesh' 'Goa' 'Chhattisgarh' 'Mizoram' 'Andhra Pradesh' 'Punjab'
 'Madhya Pradesh' 'Gujarat' 'Haryana' 'Jharkhand' 'Kerala']
Number of unique values in State_Name: 28
Unique values in Age: [42 26 78 58 22 31 68 45 52 56 67 34 21 60 51 23 39 69 72 55 47 32 20 79
 75 54 49 73 76 74 44 35 77 38 24 70 41 43 62 64 71 37 40 63 66 48 36 50
 28 33 65 61 29 25 30 57 27 53 59 46]
Number of unique values in Age: 60
Unique values in Gender: ['Female' 'Male']
Number of unique values in Gender: 2
Unique values in Diabetes: [0 1]
Number of unique values in Diabetes: 2
Unique values in Hypertension: [0 1]
Number of unique values in Hypertension: 2
Unique values in Obesity: [1 0]
Number of unique values in Obesity: 2
Unique values in Smoking: [1 0]
Number of unique values in Smoking: 2
Unique values in Alcohol_Consumption: [0 1]
Number of unique values in Alcohol_Consumption: 2
Unique values in Physical_Activity: [0 1]
Number of unique values in Physical_Activity: 2
Unique values in Diet_Score: [ 9  4  6  5  7  2  3  1 10  0  8]
Number of unique values in Diet_Score: 11
Unique values in Cholesterol_Level: [248 272 268 224 277 188 210 160 264 167 207 232 176 255 273 177 170 209
 245 225 247 169 257 185 168 281 186 249 222 213 227 260 206 208 280 200
 172 174 231 179 288 187 196 217 204 241 299 164 190 161 163 297 275 229
 258 153 192 156 238 250 220 198 256 253 197 157 279 226 216 215 259 291
 221 228 294 261 165 278 194 150 296 155 205 171 236 244 239 182 223 162
 237 293 274 252 233 262 214 154 282 212 240 269 195 199 191 180 286 267
 234 298 181 235 290 193 159 203 283 184 189 152 178 211 266 251 230 219
 218 292 284 276 265 202 254 295 201 242 166 287 285 183 243 271 289 158
 246 173 263 175 270 151]
Number of unique values in Cholesterol_Level: 150
Unique values in Triglyceride_Level: [125  51 213 250 129 218 155 275 242 174  82 115 176 270 165 122  57 269
 180 221 188  50 225 247 219 254 222 140 264  83 156  81 110  55 153 255
 146 287 265 239  84  60 191 158  94 298  75 289 267  89 211 128 141 144
 199 108 276 131 285 209 160 119 181 143 291 253 150 102 134  80  71 193
  67  79 169 157 189  63 271 262 183 201  62 229 293 130 251 284 274 120
 118 147 292 216 279 297  77 114 148 135  52 288  99 178 101 215  59 137
 240 295 107 226 299  74 294 208 187 212 217 237 245 149 164 175 244 113
 172 230 185 224  76  69 179 220 235 241 167 261  92  91  95 151 282 246
 205 162 195 138 214  78 126 257 197 116 152  61 259 106 234  98  96  64
 227 256 210 142 194 203  58  70 204  85 236 223  66 154 258 163  86 111
  87 283  72 273 103  97 117 252  90 190 196 171 281 168  73 112 277 104
 198  54 182 290 170 243 249 202 127 238 206 132 272 268 177 136 109 100
 278 296 161 263 123  65  53 231 232  68 166 173 233  88 184 121 139 159
 200 145 260 228 207 280  56  93 286 192 105 248 133 186 124 266]
Number of unique values in Triglyceride_Level: 250
Unique values in LDL_Level: [ 93 153 130 150 105 174 165 170  98  71 111 107 159 132 121  67 123 198
 147 131  83 161 103  80 129 148 164 180 126  61 172 154 173 122 127 139
 104 109 156  65 158  87 142 135 181 143 162 171  50 163  56  82 128 138
 176  74 189 125  60 115 101  99 187 102 152  59 106 112 110  66 157 134
 175 151  62 192 120 169 137 184 119  75  96 194 124  88 144  95  78 197
 118  77 113 141  76 196 166  57  72 114 191 116 149 155 160 117 177  68
  63 182 136  86  91  97  94 145 186  64  58  90 146  84 100 185 195 140
  79  85 179 188  81 178 199  73 183  53 193  54 190  69  52  89 108  55
 133  92 168  51 167  70]
Number of unique values in LDL_Level: 150
Unique values in HDL_Level: [42 47 54 79 23 22 60 72 76 74 51 67 36 37 64 29 50 69 55 25 77 44 35 71
 33 62 21 20 34 32 40 24 46 78 41 68 38 66 30 61 57 31 75 28 63 58 73 65
 52 26 49 53 59 27 48 39 43 70 45 56]
Number of unique values in HDL_Level: 60
Unique values in Systolic_BP: [ 93 134 104  91 141 110 156 157 158 166 173 165 144 152 121 155 169  92
 114 164 159 135 178 136 161 150 103 139 146 105 128 176  97 172 153 108
 179 171 118 140 125 100 145 162 154 123 119 175 112 109 130 127  95 133
 143  99 117 147 168 111 107 113 142 115 149 151 102 129  90 167 132 124
 174 137 120 122  96 163 106 170  98 148 126 177 116 160  94 138 131 101]
Number of unique values in Systolic_BP: 90
Unique values in Diastolic_BP: [119 115 117  65 109  97  77  60  67 108  71  88  94  76 116  81 106  95
  80  64  90  87  89 113  72 104 100  92  69  78  68 107  75 103  86  98
 112  91 110 118  62  70  63 101  82  96  74  85  99  83 102  79 111  93
  61  84  73  66 105 114]
Number of unique values in Diastolic_BP: 60
Unique values in Air_Pollution_Exposure: [1 0]
Number of unique values in Air_Pollution_Exposure: 2
Unique values in Family_History: [0 1]
Number of unique values in Family_History: 2
Unique values in Stress_Level: [ 4  7 10  1  9  3  6  5  8  2]
Number of unique values in Stress_Level: 10
Unique values in Healthcare_Access: [0 1]
Number of unique values in Healthcare_Access: 2
Unique values in Heart_Attack_History: [0 1]
Number of unique values in Heart_Attack_History: 2
Unique values in Emergency_Response_Time: [157 331 186 324 209  93 356 146 351 224 374 395 236 223 363 217  45  79
 357  11  17 127 300 350 318  43 294 234  73 279  85 320 227 168  78  99
 316 263  12 153  72 162 226  65  40 255 340  74 182 345  71 283 353 272
 175 141  89 132 341  84 313 253 248 346  60 307 238  10  28  95 298 247
 383 391 281  55 119  20 240 197 268 397 117 260 140 228 108 102 177 215
 328  51 285 330 244 399  50 213  31 181  42  14 276 203 386 237 109 301
  81 222 382 338 376  76  48 184 280 358 198  46 178 250 385 342 390  62
  86  63 347 389 229 288 388 266 392  22 171 322  53  27 354 199 170 343
 138 267 282 190 292 243 128 195  26 142  59  56 207 143 336 277 366 295
 160  19 131 123 326 309 371 121  38 296 104 241 116 370 154 179 375 135
 174 192 329  15 148 145 202 398 264 275 139 245 147 387 381 193 130 274
  29 134  57 261 219 297 299 149 278 164 216 201 379 315 152 302 172  87
  58 194  36  83 185 273 231  98 271  23 239 305 113 176 311  80 372 259
 258 306  52 284 167  67 377  30 136  37 378 394 124 159  92 327  64 137
 151 158  77 344 125 100 369 191 380 303 393  90  54 118 323 166 169 230
 287  66 200 101  25 396  94 308  21  35 367 165  39 286 355  34 114 249
  70 233  97 317 133 321 187 242 319 362 205 112 163  32 333 211 337 161
  47  24  49 173  82 365 180 196 126 270 364 189 210 103 129 218 262 105
 221 254  33 361 360 214 122  16 349 291 156 312 348  69 144  68 251 304
 115 110 206 120 155 246 257 111 352 290 208 235 373 265  91  75 335 150
 368 310 106 204 212 225 256 332 384  88 252  44 107  18 188 183 269  41
 325 232  61 339  13 359  96 289 334 220 293 314]
Number of unique values in Emergency_Response_Time: 390
Unique values in Annual_Income: [ 611025  174527 1760112 ...  159536  153207 1732794]
Number of unique values in Annual_Income: 9979
Unique values in Health_Insurance: [0 1]
Number of unique values in Health_Insurance: 2
Unique values in Heart_Attack_Risk: [0 1]
Number of unique values in Heart_Attack_Risk: 2
Value counts for State_Name:
State_Name
Chhattisgarh         399
Meghalaya            396
Manipur              394
Kerala               392
Arunachal Pradesh    392
Assam                384
Sikkim               379
Goa                  366
Bihar                365
Karnataka            362
Tripura              361
Maharashtra          359
West Bengal          357
Telangana            356
Uttarakhand          350
Mizoram              350
Tamil Nadu           349
Madhya Pradesh       348
Himachal Pradesh     347
Nagaland             347
Andhra Pradesh       342
Haryana              338
Uttar Pradesh        335
Punjab               333
Odisha               326
Rajasthan            326
Gujarat              324
Jharkhand            323
Name: count, dtype: int64
Value counts for Gender:
Gender
Male      5516
Female    4484
Name: count, dtype: int64

ValueError: could not convert string to float: 'Rajasthan'

In [10]:
# prompt: code for data profiling  of that datasheet

# Data type analysis
print(df.dtypes)

# Summary statistics for numerical columns
print(df.describe())

# Missing value analysis
print(df.isnull().sum())

# Unique values per column
for col in df.columns:
  print(f"Unique values in {col}: {df[col].unique()}")
  print(f"Number of unique values in {col}: {df[col].nunique()}")

# Value counts for categorical columns
for col in df.columns:
  if df[col].dtype == 'object':
    print(f"Value counts for {col}:\n{df[col].value_counts()}")

# Correlation analysis (for numerical columns)
# Select only numerical columns for correlation analysis
numerical_df = df.select_dtypes(include=['number'])  # Include only numerical columns
numerical_df.corr() # Calculate correlation on numerical data only

Patient_ID                  int64
State_Name                 object
Age                         int64
Gender                     object
Diabetes                    int64
Hypertension                int64
Obesity                     int64
Smoking                     int64
Alcohol_Consumption         int64
Physical_Activity           int64
Diet_Score                  int64
Cholesterol_Level           int64
Triglyceride_Level          int64
LDL_Level                   int64
HDL_Level                   int64
Systolic_BP                 int64
Diastolic_BP                int64
Air_Pollution_Exposure      int64
Family_History              int64
Stress_Level                int64
Healthcare_Access           int64
Heart_Attack_History        int64
Emergency_Response_Time     int64
Annual_Income               int64
Health_Insurance            int64
Heart_Attack_Risk           int64
dtype: object
        Patient_ID           Age      Diabetes  Hypertension       Obesity  \
count  10000.00000  10000.000000  10000.000000   10000.00000  10000.000000
mean    5000.50000     49.394900      0.092900       0.24690      0.303700
std     2886.89568     17.280301      0.290307       0.43123      0.459878
min        1.00000     20.000000      0.000000       0.00000      0.000000
25%     2500.75000     35.000000      0.000000       0.00000      0.000000
50%     5000.50000     49.000000      0.000000       0.00000      0.000000
75%     7500.25000     64.000000      0.000000       0.00000      1.000000
max    10000.00000     79.000000      1.000000       1.00000      1.000000

            Smoking  Alcohol_Consumption  Physical_Activity    Diet_Score  \
count  10000.000000         10000.000000       10000.000000  10000.000000
mean       0.301400             0.352800           0.595800      5.021700
std        0.458889             0.477865           0.490761      3.156394
min        0.000000             0.000000           0.000000      0.000000
25%        0.000000             0.000000           0.000000      2.000000
50%        0.000000             0.000000           1.000000      5.000000
75%        1.000000             1.000000           1.000000      8.000000
max        1.000000             1.000000           1.000000     10.000000

       Cholesterol_Level  ...  Diastolic_BP  Air_Pollution_Exposure  \
count       10000.000000  ...  10000.000000            10000.000000
mean          224.753000  ...     89.312000                0.403600
std            43.359172  ...     17.396486                0.490644
min           150.000000  ...     60.000000                0.000000
25%           187.000000  ...     74.000000                0.000000
50%           226.000000  ...     89.000000                0.000000
75%           262.000000  ...    104.000000                1.000000
max           299.000000  ...    119.000000                1.000000

       Family_History  Stress_Level  Healthcare_Access  Heart_Attack_History  \
count    10000.000000  10000.000000       10000.000000          10000.000000
mean         0.311300      5.518800           0.311000              0.152500
std          0.463048      2.866264           0.462926              0.359523
min          0.000000      1.000000           0.000000              0.000000
25%          0.000000      3.000000           0.000000              0.000000
50%          0.000000      6.000000           0.000000              0.000000
75%          1.000000      8.000000           1.000000              0.000000
max          1.000000     10.000000           1.000000              1.000000

       Emergency_Response_Time  Annual_Income  Health_Insurance  \
count             10000.000000   1.000000e+04      10000.000000
mean                206.383400   1.022062e+06          0.344700
std                 112.391711   5.605978e+05          0.475294
min                  10.000000   5.035300e+04          0.000000
25%                 110.000000   5.357838e+05          0.000000
50%                 206.000000   1.021383e+06          0.000000
75%                 304.000000   1.501670e+06          1.000000
max                 399.000000   1.999714e+06          1.000000

       Heart_Attack_Risk
count       10000.000000
mean            0.300700
std             0.458585
min             0.000000
25%             0.000000
50%             0.000000
75%             1.000000
max             1.000000

[8 rows x 24 columns]
Patient_ID                 0
State_Name                 0
Age                        0
Gender                     0
Diabetes                   0
Hypertension               0
Obesity                    0
Smoking                    0
Alcohol_Consumption        0
Physical_Activity          0
Diet_Score                 0
Cholesterol_Level          0
Triglyceride_Level         0
LDL_Level                  0
HDL_Level                  0
Systolic_BP                0
Diastolic_BP               0
Air_Pollution_Exposure     0
Family_History             0
Stress_Level               0
Healthcare_Access          0
Heart_Attack_History       0
Emergency_Response_Time    0
Annual_Income              0
Health_Insurance           0
Heart_Attack_Risk          0
dtype: int64
Unique values in Patient_ID: [    1     2     3 ...  9998  9999 10000]
Number of unique values in Patient_ID: 10000
Unique values in State_Name: ['Rajasthan' 'Himachal Pradesh' 'Assam' 'Odisha' 'Karnataka' 'Tripura'
 'Arunachal Pradesh' 'Uttarakhand' 'Manipur' 'Nagaland' 'West Bengal'
 'Bihar' 'Meghalaya' 'Maharashtra' 'Telangana' 'Tamil Nadu' 'Sikkim'
 'Uttar Pradesh' 'Goa' 'Chhattisgarh' 'Mizoram' 'Andhra Pradesh' 'Punjab'
 'Madhya Pradesh' 'Gujarat' 'Haryana' 'Jharkhand' 'Kerala']
Number of unique values in State_Name: 28
Unique values in Age: [42 26 78 58 22 31 68 45 52 56 67 34 21 60 51 23 39 69 72 55 47 32 20 79
 75 54 49 73 76 74 44 35 77 38 24 70 41 43 62 64 71 37 40 63 66 48 36 50
 28 33 65 61 29 25 30 57 27 53 59 46]
Number of unique values in Age: 60
Unique values in Gender: ['Female' 'Male']
Number of unique values in Gender: 2
Unique values in Diabetes: [0 1]
Number of unique values in Diabetes: 2
Unique values in Hypertension: [0 1]
Number of unique values in Hypertension: 2
Unique values in Obesity: [1 0]
Number of unique values in Obesity: 2
Unique values in Smoking: [1 0]
Number of unique values in Smoking: 2
Unique values in Alcohol_Consumption: [0 1]
Number of unique values in Alcohol_Consumption: 2
Unique values in Physical_Activity: [0 1]
Number of unique values in Physical_Activity: 2
Unique values in Diet_Score: [ 9  4  6  5  7  2  3  1 10  0  8]
Number of unique values in Diet_Score: 11
Unique values in Cholesterol_Level: [248 272 268 224 277 188 210 160 264 167 207 232 176 255 273 177 170 209
 245 225 247 169 257 185 168 281 186 249 222 213 227 260 206 208 280 200
 172 174 231 179 288 187 196 217 204 241 299 164 190 161 163 297 275 229
 258 153 192 156 238 250 220 198 256 253 197 157 279 226 216 215 259 291
 221 228 294 261 165 278 194 150 296 155 205 171 236 244 239 182 223 162
 237 293 274 252 233 262 214 154 282 212 240 269 195 199 191 180 286 267
 234 298 181 235 290 193 159 203 283 184 189 152 178 211 266 251 230 219
 218 292 284 276 265 202 254 295 201 242 166 287 285 183 243 271 289 158
 246 173 263 175 270 151]
Number of unique values in Cholesterol_Level: 150
Unique values in Triglyceride_Level: [125  51 213 250 129 218 155 275 242 174  82 115 176 270 165 122  57 269
 180 221 188  50 225 247 219 254 222 140 264  83 156  81 110  55 153 255
 146 287 265 239  84  60 191 158  94 298  75 289 267  89 211 128 141 144
 199 108 276 131 285 209 160 119 181 143 291 253 150 102 134  80  71 193
  67  79 169 157 189  63 271 262 183 201  62 229 293 130 251 284 274 120
 118 147 292 216 279 297  77 114 148 135  52 288  99 178 101 215  59 137
 240 295 107 226 299  74 294 208 187 212 217 237 245 149 164 175 244 113
 172 230 185 224  76  69 179 220 235 241 167 261  92  91  95 151 282 246
 205 162 195 138 214  78 126 257 197 116 152  61 259 106 234  98  96  64
 227 256 210 142 194 203  58  70 204  85 236 223  66 154 258 163  86 111
  87 283  72 273 103  97 117 252  90 190 196 171 281 168  73 112 277 104
 198  54 182 290 170 243 249 202 127 238 206 132 272 268 177 136 109 100
 278 296 161 263 123  65  53 231 232  68 166 173 233  88 184 121 139 159
 200 145 260 228 207 280  56  93 286 192 105 248 133 186 124 266]
Number of unique values in Triglyceride_Level: 250
Unique values in LDL_Level: [ 93 153 130 150 105 174 165 170  98  71 111 107 159 132 121  67 123 198
 147 131  83 161 103  80 129 148 164 180 126  61 172 154 173 122 127 139
 104 109 156  65 158  87 142 135 181 143 162 171  50 163  56  82 128 138
 176  74 189 125  60 115 101  99 187 102 152  59 106 112 110  66 157 134
 175 151  62 192 120 169 137 184 119  75  96 194 124  88 144  95  78 197
 118  77 113 141  76 196 166  57  72 114 191 116 149 155 160 117 177  68
  63 182 136  86  91  97  94 145 186  64  58  90 146  84 100 185 195 140
  79  85 179 188  81 178 199  73 183  53 193  54 190  69  52  89 108  55
 133  92 168  51 167  70]
Number of unique values in LDL_Level: 150
Unique values in HDL_Level: [42 47 54 79 23 22 60 72 76 74 51 67 36 37 64 29 50 69 55 25 77 44 35 71
 33 62 21 20 34 32 40 24 46 78 41 68 38 66 30 61 57 31 75 28 63 58 73 65
 52 26 49 53 59 27 48 39 43 70 45 56]
Number of unique values in HDL_Level: 60
Unique values in Systolic_BP: [ 93 134 104  91 141 110 156 157 158 166 173 165 144 152 121 155 169  92
 114 164 159 135 178 136 161 150 103 139 146 105 128 176  97 172 153 108
 179 171 118 140 125 100 145 162 154 123 119 175 112 109 130 127  95 133
 143  99 117 147 168 111 107 113 142 115 149 151 102 129  90 167 132 124
 174 137 120 122  96 163 106 170  98 148 126 177 116 160  94 138 131 101]
Number of unique values in Systolic_BP: 90
Unique values in Diastolic_BP: [119 115 117  65 109  97  77  60  67 108  71  88  94  76 116  81 106  95
  80  64  90  87  89 113  72 104 100  92  69  78  68 107  75 103  86  98
 112  91 110 118  62  70  63 101  82  96  74  85  99  83 102  79 111  93
  61  84  73  66 105 114]
Number of unique values in Diastolic_BP: 60
Unique values in Air_Pollution_Exposure: [1 0]
Number of unique values in Air_Pollution_Exposure: 2
Unique values in Family_History: [0 1]
Number of unique values in Family_History: 2
Unique values in Stress_Level: [ 4  7 10  1  9  3  6  5  8  2]
Number of unique values in Stress_Level: 10
Unique values in Healthcare_Access: [0 1]
Number of unique values in Healthcare_Access: 2
Unique values in Heart_Attack_History: [0 1]
Number of unique values in Heart_Attack_History: 2
Unique values in Emergency_Response_Time: [157 331 186 324 209  93 356 146 351 224 374 395 236 223 363 217  45  79
 357  11  17 127 300 350 318  43 294 234  73 279  85 320 227 168  78  99
 316 263  12 153  72 162 226  65  40 255 340  74 182 345  71 283 353 272
 175 141  89 132 341  84 313 253 248 346  60 307 238  10  28  95 298 247
 383 391 281  55 119  20 240 197 268 397 117 260 140 228 108 102 177 215
 328  51 285 330 244 399  50 213  31 181  42  14 276 203 386 237 109 301
  81 222 382 338 376  76  48 184 280 358 198  46 178 250 385 342 390  62
  86  63 347 389 229 288 388 266 392  22 171 322  53  27 354 199 170 343
 138 267 282 190 292 243 128 195  26 142  59  56 207 143 336 277 366 295
 160  19 131 123 326 309 371 121  38 296 104 241 116 370 154 179 375 135
 174 192 329  15 148 145 202 398 264 275 139 245 147 387 381 193 130 274
  29 134  57 261 219 297 299 149 278 164 216 201 379 315 152 302 172  87
  58 194  36  83 185 273 231  98 271  23 239 305 113 176 311  80 372 259
 258 306  52 284 167  67 377  30 136  37 378 394 124 159  92 327  64 137
 151 158  77 344 125 100 369 191 380 303 393  90  54 118 323 166 169 230
 287  66 200 101  25 396  94 308  21  35 367 165  39 286 355  34 114 249
  70 233  97 317 133 321 187 242 319 362 205 112 163  32 333 211 337 161
  47  24  49 173  82 365 180 196 126 270 364 189 210 103 129 218 262 105
 221 254  33 361 360 214 122  16 349 291 156 312 348  69 144  68 251 304
 115 110 206 120 155 246 257 111 352 290 208 235 373 265  91  75 335 150
 368 310 106 204 212 225 256 332 384  88 252  44 107  18 188 183 269  41
 325 232  61 339  13 359  96 289 334 220 293 314]
Number of unique values in Emergency_Response_Time: 390
Unique values in Annual_Income: [ 611025  174527 1760112 ...  159536  153207 1732794]
Number of unique values in Annual_Income: 9979
Unique values in Health_Insurance: [0 1]
Number of unique values in Health_Insurance: 2
Unique values in Heart_Attack_Risk: [0 1]
Number of unique values in Heart_Attack_Risk: 2
Value counts for State_Name:
State_Name
Chhattisgarh         399
Meghalaya            396
Manipur              394
Kerala               392
Arunachal Pradesh    392
Assam                384
Sikkim               379
Goa                  366
Bihar                365
Karnataka            362
Tripura              361
Maharashtra          359
West Bengal          357
Telangana            356
Uttarakhand          350
Mizoram              350
Tamil Nadu           349
Madhya Pradesh       348
Himachal Pradesh     347
Nagaland             347
Andhra Pradesh       342
Haryana              338
Uttar Pradesh        335
Punjab               333
Odisha               326
Rajasthan            326
Gujarat              324
Jharkhand            323
Name: count, dtype: int64
Value counts for Gender:
Gender
Male      5516
Female    4484
Name: count, dtype: int64

,Patient_ID,Age,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,Diet_Score,Cholesterol_Level,...,Diastolic_BP,Air_Pollution_Exposure,Family_History,Stress_Level,Healthcare_Access,Heart_Attack_History,Emergency_Response_Time,Annual_Income,Health_Insurance,Heart_Attack_Risk
Patient_ID,1.000000,0.009750,-0.013217,0.006447,-0.013353,-0.005823,-0.013774,0.011959,-0.006913,-0.000171,...,0.011993,0.003689,-0.003127,0.020750,-0.003233,-0.015761,0.009581,0.008703,0.000755,0.020455
Age,0.009750,1.000000,0.014416,0.000362,-0.017950,-0.004821,-0.000620,-0.003665,-0.013711,-0.017093,...,0.015541,0.012010,0.006995,0.027918,-0.009453,0.000817,-0.009703,-0.005499,-0.014164,0.015517
Diabetes,-0.013217,0.014416,1.000000,0.000503,0.011883,-0.003754,-0.003425,0.004564,0.004130,0.011206,...,0.000855,-0.007684,-0.005355,0.002528,-0.012591,0.005105,-0.004761,-0.013209,-0.012486,-0.009278
Hypertension,0.006447,0.000362,0.000503,1.000000,-0.021602,0.013566,-0.005855,0.019834,-0.000557,0.003471,...,0.008208,-0.021029,-0.006311,0.010283,-0.003937,-0.001627,0.014022,0.000021,0.003384,-0.001228
Obesity,-0.013353,-0.017950,0.011883,-0.021602,1.000000,-0.012488,0.000249,0.012211,0.009928,0.003271,...,-0.009770,-0.003428,0.012954,-0.024856,0.001171,0.011407,0.014716,0.000961,0.004185,-0.002004
Smoking,-0.005823,-0.004821,-0.003754,0.013566,-0.012488,1.000000,-0.027975,-0.019869,0.005772,0.008381,...,-0.009187,-0.008196,0.002702,0.011203,0.005012,0.004465,-0.005621,0.016120,0.003244,-0.012504
Alcohol_Consumption,-0.013774,-0.000620,-0.003425,-0.005855,0.000249,-0.027975,1.000000,-0.009374,0.011434,-0.010791,...,-0.002908,0.005587,0.008467,-0.007691,-0.005519,0.007556,-0.002171,-0.001635,-0.005769,-0.017283
Physical_Activity,0.011959,-0.003665,0.004564,0.019834,0.012211,-0.019869,-0.009374,1.000000,-0.001762,0.012979,...,0.009291,-0.016468,-0.011762,-0.005404,0.032163,-0.000337,0.002487,0.001603,0.000976,0.005968
Diet_Score,-0.006913,-0.013711,0.004130,-0.000557,0.009928,0.005772,0.011434,-0.001762,1.000000,0.008693,...,-0.015253,-0.001458,-0.004007,-0.002405,0.002431,0.000080,-0.003211,-0.002154,-0.004053,0.010623
Cholesterol_Level,-0.000171,-0.017093,0.011206,0.003471,0.003271,0.008381,-0.010791,0.012979,0.008693,1.000000,...,0.006900,-0.001557,0.002665,0.010012,0.018018,0.011309,-0.002897,0.006885,0.010062,-0.003054
Triglyceride_Level,0.018366,-0.013232,0.017872,0.009371,0.002139,-0.002662,-0.000968,-0.002858,-0.005151,-0.011515,...,0.000063,-0.003092,0.005619,-0.010697,0.020059,0.002946,-0.002838,0.015050,0.007077,-0.004815
LDL_Level,-0.000265,-0.002799,-0.005501,0.012035,0.000243,-0.010791,-0.001768,0.012262,0.000114,-0.020865,...,0.023182,0.000193,0.000702,0.018363,0.003363,0.008933,-0.007101,-0.007202,-0.008803,0.021228
HDL_Level,0.004500,-0.004856,0.004421,-0.013453,0.009412,-0.000190,0.009987,0.002999,-0.004623,-0.009974,...,-0.005017,0.014244,-0.016477,-0.004331,0.004663,0.001189,-0.011671,-0.001443,-0.011143,0.011884
Systolic_BP,-0.013919,0.018981,-0.001178,-0.010069,0.006818,-0.002284,-0.003659,0.016604,-0.005085,-0.006290,...,-0.007127,0.008731,0.004899,0.005599,0.000137,0.011827,0.001409,-0.007076,0.003515,-0.002293
Diastolic_BP,0.011993,0.015541,0.000855,0.008208,-0.009770,-0.009187,-0.002908,0.009291,-0.015253,0.006900,...,1.000000,0.000700,-0.012530,0.011592,0.004827,-0.015523,-0.002847,0.006307,0.003442,-0.003951
Air_Pollution_Exposure,0.003689,0.012010,-0.007684,-0.021029,-0.003428,-0.008196,0.005587,-0.016468,-0.001458,-0.001557,...,0.000700,1.000000,0.001142,0.001573,0.015325,-0.005380,-0.016213,-0.000233,0.007201,-0.006501
Family_History,-0.003127,0.006995,-0.005355,-0.006311,0.012954,0.002702,0.008467,-0.011762,-0.004007,0.002665,...,-0.012530,0.001142,1.000000,-0.003091,0.000400,0.006168,0.005999,0.008338,0.004067,0.001376
Stress_Level,0.020750,0.027918,0.002528,0.010283,-0.024856,0.011203,-0.007691,-0.005404,-0.002405,0.010012,...,0.011592,0.001573,-0.003091,1.000000,-0.003502,-0.009042,0.003164,-0.018294,-0.007437,-0.012176
Healthcare_Access,-0.003233,-0.009453,-0.012591,-0.003937,0.001171,0.005012,-0.005519,0.032163,0.002431,0.018018,...,0.004827,0.015325,0.000400,-0.003502,1.000000,0.006445,-0.017754,0.001722,-0.005462,-0.011861
Heart_Attack_History,-0.015761,0.000817,0.005105,-0.001627,0.011407,0.004465,0.007556,-0.000337,0.000080,0.011309,...,-0.015523,-0.005380,0.006168,-0.009042,0.006445,1.000000,-0.001964,0.003947,-0.012096,-0.000344
Emergency_Response_Time,0.009581,-0.009703,-0.004761,0.014022,0.014716,-0.005621,-0.002171,0.002487,-0.003211,-0.002897,...,-0.002847,-0.016213,0.005999,0.003164,-0.017754,-0.001964,1.000000,-0.005241,-0.012286,0.015149
Annual_Income,0.008703,-0.005499,-0.013209,0.000021,0.000961,0.016120,-0.001635,0.001603,-0.002154,0.006885,...,0.006307,-0.000233,0.008338,-0.018294,0.001722,0.003947,-0.005241,1.000000,-0.001699,0.007378
Health_Insurance,0.000755,-0.014164,-0.012486,0.003384,0.004185,0.003244,-0.005769,0.000976,-0.004053,0.010062,...,0.003442,0.007201,0.004067,-0.007437,-0.005462,-0.012096,-0.012286,-0.001699,1.000000,-0.000235
Heart_Attack_Risk,0.020455,0.015517,-0.009278,-0.001228,-0.002004,-0.012504,-0.017283,0.005968,0.010623,-0.003054,...,-0.003951,-0.006501,0.001376,-0.012176,-0.011861,-0.000344,0.015149,0.007378,-0.000235,1.000000